---
- name: create file /etc/hosts 
  hosts: all
  tasks:
    - name: copy from files/hosts to /etc/hosts
      # cp -f files/hosts /etc/hosts
      copy:
        src: files/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        # force: yes
