---
- name: 패키지 설치 예제
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
    - name: 변수 포함
      include_vars: vars/main.yml

    - name: 작업 포함
      include_tasks: tasks/main.yml

    - name: 방화벽 설치
      yum:
        name: "{{ firewall }}"
        state: latest

    - name: Start the firewall
      service:
        name: "{{ firewall }}"
        state: started
        enabled: true

    - name: Open the port for the web server
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true

    - name: Create index.html
      copy:
        content: "{{ ansible_fqdn }}({{ ansible_default_ipv4.address }}) has been customized by Ansible\n"
        dest: "{{ web_root }}/index.html"