---
- name: 결과 폴더 만들기
  hosts: localhost
  gather_facts: no
  tasks:
  - name: result 디렉토리 삭제
    file:
      path: results
      state: absent

- name: 하드웨어 정보 수집하기
  hosts: all
  become: true
  gather_facts: yes
  tasks:
  # 1. 템플릿 파일 배포 (/root/hwreport.txt)
  # 2. 하드웨어 정보 수집
  # 3. 하드웨어 정보 파일 수집

  - name: 1. 템플릿 파일 배포 (/root/hwreport.txt)
    copy:
      src: files/hwreport.txt
      dest: /root/hwreport.txt
      owner: root
      group: root
      mode: '0400'

  # 2. 하드웨어 정보 수집
  # 호스트 네임, 총 메모리, 바이오스 버전, 디스크 크기
  - name: 호스트 네임 수집
    replace:
      path: /root/hwreport.txt
      regexp: 'inventoryhostname'
      replace: "{{ansible_hostname}}"

  - name: 총 메모리 수집
    replace:
      path: /root/hwreport.txt
      regexp: 'totalmem'
      replace: "{{ansible_memtotal_mb}}"

  - name: 바이오스 버전 수집
    replace:
      path: /root/hwreport.txt
      regexp: 'biosversion'
      replace: "{{ansible_bios_version}}"

  - name: /dev/sda 디스크 크기 정보 수집
    replace:
      path: /root/hwreport.txt
      regexp: 'sdasize'
      replace: "{{ansible_devices.sda.size}}"
  
  - name: 하드웨어 정보 파일 수집
    fetch:
      src: /root/hwreport.txt
      # dest: results 로 지정했을 때
      # dest: results/hwreport-{{inventory_hostname}}.txt로 지정했을때
      dest: results/hwreport-{{inventory_hostname}}.txt
      flat: yes

    
