---
# 1. 방화벽 서비스 OFF: http, https, mysql => firewalld
# 2. 서비스 disable -httpd, mariadb -> service
# 3. 서비스 디렉토리 삭제 - /var/www/html -> fire recurlsive
# 4. 패키지 삭제 - .... => yum 

- name: 웹 서버 구성 및 DB 서버 복구 과정
  hosts: webservers
  tasks:
  - name: 방화벽 서비스 OFF
    firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: disabled
    loop:
      - http
      - https
      - mysql
  
  - name: 서비스 disable
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    ignore_errors: yes
    loop:
      - httpd
      - mariadb 

  - name: "웹 서비스 디렉토리 삭제"
    file: 
      path: /var/www/html/
      state: absent
      
  - name: "패키지 삭제"
    yum: 
      name:
        - httpd
        - mod_ssl
        - mariadb
        - mariadb-server
        - php
        - php-mysqlnd
        - php-pdo
        - python3-pip
      state: absent
