---
- name: MariaDB 패키지 설치
  hosts: databases
  # vars:
  #   pkg_db::
  #     - mariadb-server
  #     - python3-PyMySQL
  #   db_service: mariadb
  #   resources_url: http://ansible.example.com
  #   config_file_url: "{{ resources_url }}/my.cnf.standard"
  #   config_file_dst: /etc/my.cnf
  vars_files:
    - vars/db.yml
  tasks:
  - name: DB 패키지 설치
    yum:
      name: "{{ pkg_db }}"
      state: present
    notify:
      - set db init
  - name: "추가 pip3 패키지 설치"
    pip:
      name: pymysql
      executable: pip3

  - name: DB 서비스 기동
    service:
      name: "{{ svc_db }}"
      state: started
      enabled: true

  - name: DB 설정 파일 수정
    get_url:
      url: "{{ conf_src_url }}"
      dest: "{{ conf_dest_file }}"
      owner: mysql
      group: mysql
      force: yes
    notify:
      - restart db service

  handlers:
  - name: restart db service
    service:
      name: "{{ svc_db }}"
      state: restarted

  - name: set db init
    become: true
    expect:
      command: mysql_secure_installation
      responses:
        'Enter current password for root': ""
        'Switch to unix_socket authentication': 'Y'
        'Change the root password?': 'Y'
        'New password': '1234'
        'Re-enter new password': '1234'
        'Remove anonymous users?': 'Y'
        'Disallow root login remotely?': 'Y'
        'Remove test database and access to it?': 'Y'
        'Reload privilege tables now?': 'Y'
      timeout: 1
