---
- name: MariaDB 패키지 삭제
  hosts: databases
  gather_facts: no
  vars_files:
    - vars/db.yml
  tasks:
  - name: DB 서비스 종료
    service:
      name: "{{ svc_db }}"
      state: stopped
      enabled: no

  - name: DB 패키지 삭제
    yum:
      name: "{{ pkg_db }}"
      state: absent

  - name: "/ect/my.cnf/파일 삭제"
    file: 
      path: "{{conf_dest_file}}"
      stae: absent


