---

# play 1 -web1
- name: 웹 서버 설정과 확인
  hosts: web1
  tasks: 
# 1) 패키지 설치 - httpd, mod_ssl, firewalld
  - name: "(1) 패키지 설치"
    yum:
      name:
        - httpd
        - mod_ssl
        - firewalld
      state: latest

# 2) 웹 서비스 설정 - /var/www/html/index.html
  - name: "(2) 웹서비스 설정"
    copy:
      content: |
        <html>
        <h1>
          <center>web1.example.com_정훈 </center>
        </h1>
        </html>
      dest: /var/www/html/index.html
# 3) 서비스 기동 - httpd, firewalld 
  - name: "(3)서비스 기동"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd
      - firewalld
# 4) 방화벽 등록 - http, https
  - name: "(4) 방화벽 등록"
    firewalld:
      port: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - 80/tcp
      - 443/tcp

    
# play 2 - localhost 
- name: 웹요청  
  hosts: localhost
  become: no
  tasks:
# 1) 웹 확인 - 웹 요청 - curl http://web1.example.com
  - name: 
    uri:
      url: http://web1
      return_content: true
      status_code: 200

